from typing import List, Dict, Any, Optional
from langchain_core.messages import BaseMessage
from typing import List, Dict, Any, Optional, TypedDict

class AgentState(TypedDict):
    """
    Represents the state of the LangGraph agent during portfolio analysis.

    Attributes:
        documents (List[Dict[str, Any]]): A list of dictionaries, where each dictionary
                                          represents a loaded document. Each document
                                          should have at least 'content' and 'metadata' keys.
        sections_to_process (List[str]): A list of section titles that still need to be
                                         processed by the agent (e.g., "Overview", "Financial Review").
        completed_sections (List[Dict[str, Any]]): A list of dictionaries, where each
                                                  dictionary represents a completed section
                                                  of the analysis, including its content,
                                                  references, and any other relevant metadata.
        current_section (Optional[str]): The title of the section currently being processed.
                                         None if no section is currently active.
        loop_count (int): The current iteration count for the review loop of the
                          `current_section`. Used to limit the number of review cycles.
        critique (Optional[Dict[str, Any]]): The critique generated by the Reviewer Node
                                            for the `current_section`. Contains feedback
                                            and search terms for refinement.
        messages (List[BaseMessage]): A list of messages exchanged during the agent's
                                      execution, useful for debugging and tracing.
    """
    documents: List[Dict[str, Any]]
    sections_to_process: List[str]
    completed_sections: List[Dict[str, Any]]
    current_section: Optional[str]
    loop_count: int
    critique: Optional[Dict[str, Any]]
    messages: List[BaseMessage]